export type HeroManualContent = { introduction: string; battleStyle: string; skills: Record<string, string> };

export const heroManualContent: Record<string, HeroManualContent> = {
  "hero.priest.comprehensiveness": { introduction: "A versatile priest who balances holy restoration with shadow pressure.", battleStyle: "Supports wounded allies while maintaining ranged pressure.", skills: { "skill.priest.holy_smite": "A direct holy attack against one enemy.", "skill.priest.shadow_word_pain": "Marks one enemy with a continuing shadow affliction.", "skill.priest.binding_heal": "Restores an ally and also helps the caster." } },
  "hero.priest.discipline": { introduction: "A disciplined priest who turns holy conviction toward allies or enemies.", battleStyle: "Adapts between healing, protection, and multi-target pressure.", skills: { "skill.priest.penance": "Heals an ally or damages an enemy according to the chosen target.", "skill.priest.holy_word_redemption": "Places a restorative holy effect on one ally.", "skill.priest.holy_word_punishment": "Pressures multiple enemies with a holy punishment effect." } },
  "hero.paladin.retribution": { introduction: "A battle-ready paladin who builds crusading momentum.", battleStyle: "Alternates steady melee pressure with empowered holy attacks and support.", skills: { "skill.paladin.hammer_of_anger": "A ranged holy attack that benefits from crusader momentum.", "skill.paladin.crusader_strike": "A melee strike that builds Wrath of Crusader.", "skill.paladin.flash_of_light": "Restores an ally, strengthened by Wrath of Crusader." } },
  "hero.paladin.protection": { introduction: "A resilient paladin who withstands harm and protects the line.", battleStyle: "Absorbs pressure, disrupts enemies, and supports the team over time.", skills: { "skill.paladin.hammer_of_revenge": "A ranged holy retaliation that responds to the caster's debuffs.", "skill.paladin.shield_of_righteous": "A melee shield strike that strengthens the caster's defence.", "skill.paladin.heroric_charge": "A ranged charge that can disrupt and draw hostility.", "skill.paladin.holy_aura": "Passive: while alive, restores each living teammate at round start." } },
  "hero.paladin.holy": { introduction: "A holy paladin devoted to resilient protection and restoration.", battleStyle: "Combines healing, cleansing, protection, and ranged holy pressure.", skills: { "skill.paladin.purify_healing": "Restores one ally and can cleanse an eligible harmful effect.", "skill.paladin.holy_blast": "A ranged holy attack that can affect multiple enemies.", "skill.paladin.shield_of_protection": "Protects the caster from incoming damage for a limited time." } },
  "hero.mage.comprehensiveness": { introduction: "An arcane scholar who commands elemental and arcane attacks.", battleStyle: "Uses ranged magic to exploit opponents and control their pace.", skills: { "skill.mage.fireball": "A ranged fire attack against one enemy.", "skill.mage.arcane_missiles": "Arcane projectiles directed at multiple enemies.", "skill.mage.frost_bolt": "A ranged frost attack that can inflict Cold." } },
  "hero.warrior.defence": { introduction: "A shield-bearing warrior built to hold ground under pressure.", battleStyle: "Breaks armour, disrupts enemies, and reinforces personal defence.", skills: { "skill.warrior.devastate": "A forceful attack against one enemy.", "skill.warrior.shield_bash": "A shield attack that can stun.", "skill.warrior.thunder_pot": "A defensive technique with enemy-facing pressure." } },
  "hero.warrior.weapon_master": { introduction: "A seasoned weapon master who pursues decisive physical strikes.", battleStyle: "Finishes vulnerable enemies and weakens durable defenders.", skills: { "skill.warrior.fatal_strike": "A decisive strike that can reduce healing received.", "skill.warrior.armor_crush": "A crushing strike that can weaken armour.", "skill.warrior.antivenom_potion": "A self-directed recovery and poison-resistance action." } },
  "hero.warrior.berserker": { introduction: "A relentless warrior who thrives on aggressive momentum.", battleStyle: "Pressures several enemies and turns fury into force.", skills: { "skill.warrior.moon_slash": "A sweeping attack against multiple enemies.", "skill.warrior.warlust": "A self-buff that increases battle aggression.", "skill.warrior.strike_of_meteorite": "A heavy single-enemy attack." } },
  "hero.rogue.comprehensiveness": { introduction: "A quick rogue who uses precision, poison, and evasive movement.", battleStyle: "Prioritises vulnerable enemies while avoiding retaliation.", skills: { "skill.rogue.sharp_blade": "A swift melee strike that can cause bleeding.", "skill.rogue.poisoned_dagger": "A ranged dagger attack that can apply poison.", "skill.rogue.shadow_evasion": "A self-buff that improves evasion." } },
};
