"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AssetImage } from "@/components/battle/AssetImage";
import { fetchHeroGalleryRoster, fetchPlayerProgression } from "@/lib/battle/liveProvider";
import type { HeroGalleryDefinition } from "@/lib/battle/types";
import { heroManualContent } from "@/lib/manual/heroManualContent";

type State = { heroes: HeroGalleryDefinition[]; owned: Set<string> | null; error: string | null };
export function HeroGalleryExperience() {
  const [state, setState] = useState<State>({ heroes: [], owned: null, error: null }); const [faculty, setFaculty] = useState("All"); const [selected, setSelected] = useState<string | null>(null);
  useEffect(() => { let active=true; Promise.all([fetchHeroGalleryRoster(), fetchPlayerProgression().catch(()=>null)]).then(([heroes, progress])=>{if(active)setState({heroes,owned:progress?new Set(progress.unlockedHeroDefinitionIds):null,error:null});}).catch(()=>active&&setState({heroes:[],owned:null,error:"Hero Gallery data is unavailable. Please retry from the Stage Map."})); return()=>{active=false}; },[]);
  const faculties=useMemo(()=>["All",...new Set(state.heroes.map(h=>h.faculty))],[state.heroes]); const heroes=state.heroes.filter(h=>faculty==="All"||h.faculty===faculty); const hero=state.heroes.find(h=>h.definitionId===(selected??heroes[0]?.definitionId))??null; const content=hero?heroManualContent[hero.definitionId]:null;
  return <main className="manual-page hero-gallery-page"><Link className="manual-back" href="/stages?manual=open">← Back to Game Manual</Link><header><small>GAME MANUAL</small><h1>Hero Gallery</h1><p>Starting attributes are generated within the displayed configured ranges. They are not fixed character-sheet values or a promise of a specific battle roll.</p></header>{state.error?<p role="alert" className="manual-error">{state.error}</p>:!state.heroes.length?<p className="manual-loading">Loading the approved hero definitions…</p>:<><div className="manual-filter" aria-label="Filter heroes by faculty">{faculties.map(value=><button key={value} type="button" aria-pressed={faculty===value} onClick={()=>setFaculty(value)}>{value}</button>)}</div><div className="gallery-layout"><section className="gallery-cards" aria-label="Approved heroes">{heroes.map(item=>{const ownership=state.owned===null?"Ownership unavailable":state.owned.has(item.definitionId)?"Owned":"Locked";return <button key={item.definitionId} type="button" aria-pressed={hero?.definitionId===item.definitionId} onClick={()=>setSelected(item.definitionId)}><AssetImage request={{kind:"portrait",key:item.definitionId,name:item.displayName,className:item.faculty}}/><span><strong>{item.faculty}</strong><small>{item.specialization}</small><em>{ownership}</em></span></button>})}</section>{hero&&content&&<article className="hero-profile" aria-live="polite"><AssetImage request={{kind:"figure",key:hero.definitionId,name:hero.displayName,className:hero.faculty}} className="hero-profile-art"/><div><small>{hero.faculty}</small><h2>{hero.specialization}</h2><p>{content.introduction}</p><h3>Battle Style</h3><p>{content.battleStyle}</p><h3>Configured Starting Ranges</h3><dl>{hero.startingStatRanges.map(r=><div key={r.id}><dt>{r.label}</dt><dd>{r.minimum}–{r.maximum}</dd></div>)}</dl><h3>Magic Resistance Schools</h3><dl>{hero.startingResistanceRanges.map(r=><div key={r.id}><dt>{r.label}</dt><dd>{r.minimum}–{r.maximum}</dd></div>)}</dl><h3>Active Skills</h3>{hero.skills.filter(s=>!s.isPassive).map(s=><details key={s.skillId}><summary>{s.displayName}</summary><p>{content.skills[s.skillId]??"Authoritative skill details are available in battle."}</p></details>)}<h3>Passive</h3>{hero.skills.filter(s=>s.isPassive).length?hero.skills.filter(s=>s.isPassive).map(s=><details key={s.skillId}><summary>{s.displayName}</summary><p>{content.skills[s.skillId]}</p></details>):<p className="manual-na">N/A</p>}<h3>Availability</h3><p>{state.owned===null?"Ownership unavailable without an active save slot.":state.owned.has(hero.definitionId)?"Owned in the active save slot.":hero.unlockSource?.kind==="stageReward"?`Locked · Reward from ${hero.unlockSource.stageDisplayName}, Battle ${hero.unlockSource.battleIndex}.`:hero.unlockSource?.kind==="starter"?"Starter definition for a new save slot.":"Locked · No current unlock route."}</p></div></article>}</div></>}</main>;
}
